services:
  db:
    image: postgres:18
    container_name: tft_stats_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: tft_stats_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build: ./backend
    container_name: tft_backend
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"

  worker:
    build: ./backend
    container_name: tft_worker
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: uv run celery -A celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - /app/.venv
    env_file: .env
    depends_on:
      - redis
      - db
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"

  beat:
    build: ./backend
    container_name: tft_beat
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: uv run celery -A celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
      - /app/.venv
    env_file: .env
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"

  flower:
    build: ./backend
    container_name: tft_flower
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: uv run celery -A celery_app flower --port=5555
    volumes:
      - ./backend:/app
      - /app/.venv
    ports:
      - "5555:5555"
    env_file: .env
    depends_on:
      - redis
      - worker
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"

volumes:
  postgres_data: