"""initial_full_schema_v2

Revision ID: 0633991cc82a
Revises: 
Create Date: 2026-04-02 19:46:08.864415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0633991cc82a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riot_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('ability_name', sa.String(), nullable=True),
    sa.Column('ability_desc', sa.Text(), nullable=True),
    sa.Column('ability_variables', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('riot_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riot_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effects', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('riot_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed_item_stats', sa.Boolean(), nullable=False),
    sa.Column('processed_champion_stats', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.create_index(op.f('ix_matches_processed_champion_stats'), 'matches', ['processed_champion_stats'], unique=False)
    op.create_index(op.f('ix_matches_processed_item_stats'), 'matches', ['processed_item_stats'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riot_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traits_riot_id'), 'traits', ['riot_id'], unique=True)
    op.create_table('champion_item_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('patch', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_champion_item_stats_champion_id'), 'champion_item_stats', ['champion_id'], unique=False)
    op.create_index(op.f('ix_champion_item_stats_item_id'), 'champion_item_stats', ['item_id'], unique=False)
    op.create_index(op.f('ix_champion_item_stats_match_id'), 'champion_item_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_champion_item_stats_patch'), 'champion_item_stats', ['patch'], unique=False)
    op.create_index(op.f('ix_champion_item_stats_puuid'), 'champion_item_stats', ['puuid'], unique=False)
    op.create_table('champion_item_valid_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id', 'champion_id', 'item_id')
    )
    op.create_table('champion_roles',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('champion_id', 'role_id')
    )
    op.create_table('champion_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.Column('patch', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_champion_stats_champion_id'), 'champion_stats', ['champion_id'], unique=False)
    op.create_index(op.f('ix_champion_stats_match_id'), 'champion_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_champion_stats_patch'), 'champion_stats', ['patch'], unique=False)
    op.create_index(op.f('ix_champion_stats_puuid'), 'champion_stats', ['puuid'], unique=False)
    op.create_table('champion_traits',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ),
    sa.PrimaryKeyConstraint('champion_id', 'trait_id')
    )
    op.create_table('item_roles',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_roles')
    op.drop_table('champion_traits')
    op.drop_index(op.f('ix_champion_stats_puuid'), table_name='champion_stats')
    op.drop_index(op.f('ix_champion_stats_patch'), table_name='champion_stats')
    op.drop_index(op.f('ix_champion_stats_match_id'), table_name='champion_stats')
    op.drop_index(op.f('ix_champion_stats_champion_id'), table_name='champion_stats')
    op.drop_table('champion_stats')
    op.drop_table('champion_roles')
    op.drop_table('champion_item_valid_pairs')
    op.drop_index(op.f('ix_champion_item_stats_puuid'), table_name='champion_item_stats')
    op.drop_index(op.f('ix_champion_item_stats_patch'), table_name='champion_item_stats')
    op.drop_index(op.f('ix_champion_item_stats_match_id'), table_name='champion_item_stats')
    op.drop_index(op.f('ix_champion_item_stats_item_id'), table_name='champion_item_stats')
    op.drop_index(op.f('ix_champion_item_stats_champion_id'), table_name='champion_item_stats')
    op.drop_table('champion_item_stats')
    op.drop_index(op.f('ix_traits_riot_id'), table_name='traits')
    op.drop_table('traits')
    op.drop_table('roles')
    op.drop_index(op.f('ix_matches_processed_item_stats'), table_name='matches')
    op.drop_index(op.f('ix_matches_processed_champion_stats'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('items')
    op.drop_table('champions')
    # ### end Alembic commands ###
