"""fix_valid_pairs_primary_key

Revision ID: 088ace2fd457
Revises: 0633991cc82a
Create Date: 2026-04-11 11:06:25.626262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088ace2fd457'
down_revision: Union[str, Sequence[str], None] = '0633991cc82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('champion_item_valid_pairs_pkey', 'champion_item_valid_pairs', type_='primary')
    op.create_primary_key('champion_item_valid_pairs_pkey', 'champion_item_valid_pairs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('champion_item_valid_pairs_pkey', 'champion_item_valid_pairs', type_='primary')
    op.create_primary_key('champion_item_valid_pairs_pkey', 'champion_item_valid_pairs', ['id', 'champion_id', 'item_id'])
    # ### end Alembic commands ###
