#Hardcoded data needed for db initialization(champions, traits, items) that is absent from the json
#like roles of champions, active artifacts and types of traits(origins/classes)

#Artifacts are hardcoded because of inability to find a consistent way to identify all of
#the active artifacts for a given set. Riot API/ Community dragon keeps data on all old/inactive artifacts
ARTIFACTS = {
    "TFT_Item_Artifact_TheIndomitable", "TFT9_Item_OrnnHullbreaker", 
    "TFT17_Item_Artifact_EkkoArtifact", "TFT7_Item_ShimmerscaleMogulsMail", 
    "TFT7_Item_ShimmerscaleGamblersBlade", "TFT_Item_Artifact_EternalPact",
    "TFT_Item_Artifact_HellfireHatchet", "TFT_Item_Artifact_LichBane", 
    "TFT_Item_Artifact_Fishbones", "TFT_Item_Artifact_TitanicHydra", 
    "TFT_Item_Artifact_AegisOfDusk", "TFT17_Item_Artifact_YasuoArtifact",
    "TFT17_Item_Artifact_ThreshLantern", "TFT17_Item_Artifact_KayleArtifact_Radiant", 
    "TFT17_Item_Artifact_KayleArtifact", "TFT4_Item_OrnnZhonyasParadox", 
    "TFT_Item_Artifact_LudensTempest", "TFT_Item_Artifact_RapidFirecannon",
    "TFT_Item_Artifact_StatikkShiv", "TFT9_Item_OrnnHorizonFocus", 
    "TFT_Item_Artifact_AegisOfDawn", "TFT17_Item_Artifact_EvelynnArtifact", 
    "TFT17_Item_Artifact_SorakaArtifact", "TFT17_Item_Artifact_VarusArtifact",
    "TFT_Item_Artifact_Dawncore", "TFT17_Item_Artifact_AhriArtifact", 
    "TFT_Item_Artifact_LightshieldCrest", "TFT4_Item_OrnnDeathsDefiance", 
    "TFT_Item_Artifact_BlightingJewel", "TFT_Item_Artifact_TalismanOfAscension",
    "TFT4_Item_OrnnInfinityForce", "TFT_Item_Artifact_Mittens", 
    "TFT_Item_Artifact_NavoriFlickerblades", "TFT_Item_Artifact_WitsEnd", 
    "TFT_Item_Artifact_HorizonFocus", "TFT_Item_Artifact_ProwlersClaw", 
    "TFT_Item_Artifact_VoidGauntlet", "TFT_Item_Artifact_SilvermereDawn", 
    "TFT_Item_Artifact_SeekersArmguard", "TFT4_Item_OrnnTheCollector", 
    "TFT_Item_Artifact_CappaJuice"
}

#Mapping for traits for their types(unique,class or origin)
TRAIT_MAPPING = {
    # Unique
    "Doomer": "Unique", "Eradicator": "Unique", "Gun Goddess": "Unique", 
    "Galaxy Hunter": "Unique", "Bulwark": "Unique", "Commander": "Unique", 
    "Redeemer": "Unique", "Party Animal": "Unique", "Oracle": "Unique", 
    "Divine Duelist": "Unique", "Dark Lady": "Unique", "Factory New": "Unique",

    # Origins
    "Psionic": "Origin", "Anima": "Origin",
    "Dark Star": "Origin", "Primordian": "Origin", "Space Groove": "Origin", 
    "Mecha": "Origin", "N.O.V.A.": "Origin", "Stargazer": "Origin", 
    "Timebreaker": "Origin", "Arbiter": "Origin", "Shepherd": "Origin", "Meeple": "Origin",

    # Classes
    "Challenger": "Class", "Vanguard": "Class", "Marauder": "Class", 
    "Rogue": "Class", "Brawler": "Class",  "Fateweaver": "Class", 
    "Bastion": "Class", "Conduit": "Class", "Replicator" : "Class",
    "Voyager": "Class", "Sniper": "Class"
}

ROLES_LIST = ["Tank", "AD Fighter", "AP Fighter", "AD Caster", "AP Caster", "AD AA", "AP AA"]

CHAMPION_ROLE_MAPPING = {
    "Aatrox": ["Tank", "AD Fighter"],
    "Akali": ["AD Fighter"],
    "Aurelion Sol": ["AP Caster"],
    "Aurora": ["AP Caster"],
    "Bard": ["AP Caster"], 
    "Bel'Veth": ["AD Fighter", "AD AA"],
    "Blitzcrank": ["Tank", "AP Fighter"],
    "Briar": ["AD Fighter"],
    "Caitlyn": ["AD AA"],
    "Cho'Gath": ["Tank"], 
    "Corki": ["AD Caster"],
    "Diana": ["AP Fighter"],
    "Ezreal": ["AD Caster"],
    "Fiora": ["AD Fighter"],
    "Fizz": ["AP Fighter"],
    "Gnar": ["AD AA"], 
    "Gragas": ["Tank"],
    "Graves": ["AD Fighter", "AD Caster", "AD AA"],
    "Gwen": ["AP Fighter"],
    "Illaoi": ["Tank"],
    "Jax": ["Tank"],
    "Jhin": ["AD AA", "AD Caster"], 
    "Jinx": ["AD AA"],
    "Kai'Sa": ["AD Caster"],
    "Karma": ["AP Caster"],
    "Kindred": ["AD AA"],
    "LeBlanc": ["AP AA"], 
    "Leona": ["Tank"],
    "Lissandra": ["AP Caster"],
    "Lulu": ["AP Caster", "AP AA"],
    "Maokai": ["Tank"],
    "Meepsie": ["Tank", "AP Fighter"],
    "Master Yi": ["AD Fighter"], 
    "Milio": ["AP Caster"],
    "Miss Fortune": ["AD Caster"],
    "Mordekaiser": ["Tank"],
    "Morgana": ["AP Fighter"], 
    "Nami": ["AP Caster"],
    "Nasus": ["Tank", "AD Fighter"],
    "Nunu & Willump": ["Tank"],
    "Ornn": ["Tank"],
    "Pantheon": ["Tank"], 
    "Poppy": ["Tank", "AD Fighter"],
    "Pyke": ["AD Fighter"],
    "Rammus": ["Tank"],
    "Rek'Sai": ["Tank"],
    "Rhaast": ["Tank"], 
    "Riven": ["AD Fighter"],
    "Samira": ["AD Caster"],
    "Shen": ["Tank"],
    "Sona": ["AP Caster"],
    "Tahm Kench": ["Tank"], 
    "Talon": ["AD Fighter"],
    "Teemo": ["AP AA"],
    "The Mighty Mech": ["Tank", "AD Fighter"],
    "Twisted Fate": ["AP Caster"], 
    "Urgot": ["AD Fighter"],
    "Veigar": ["AP Caster"],
    "Vex": ["AP AA"],
    "Viktor": ["AP Caster"],
    "Xayah": ["AD AA"], 
    "Zed": ["Tank", "AD Fighter"],
    "Zoe": ["AP Caster"]
}

ITEM_ROLE_MAPPING = {
    # Artifacts
    "Wit's End": ["AD AA", "AP Fighter", "AP AA"],
    "The Indomitable": ["Tank"],
    "Talisman Of Ascension": ["Tank", "AD Fighter", "AD AA", "AP Fighter", "AP AA"],
    "Mittens": ["AD Fighter", "AP Fighter"],
    "Sniper's Focus": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Luden's Tempest": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Gambler's Blade": ["AD Caster", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Hellfire Hatchet": ["AD Fighter", "AP Fighter"],
    "Rapid Firecannon": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Seeker's Armguard": ["Tank", "AD Fighter", "AP Fighter"],
    "Eternal Pact": ["AP Caster", "AP Fighter"],
    "Aegis of Dawn": ["Tank"],
    "Blighting Jewel": ["AP Caster", "AP Fighter"],
    "Void Gauntlet": ["Tank"],
    "Infinity Force": ["Tank", "AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Mogul's Mail": ["Tank"],
    "Fishbones": ["AD Caster", "AD Fighter", "AD AA", "AP AA"],
    "Hullcrusher": ["Tank", "AD Fighter", "AP Fighter"],
    "Cappa Juice": ["AD Caster", "AD Fighter", "AD AA", "AP AA"],
    "Death's Defiance": ["AD Fighter"],
    "Prowler's Claw": ["AD Fighter"],
    "Horizon Focus": ["Tank", "AP Caster", "AP Fighter"],
    "Titanic Hydra": ["Tank", "AD Fighter", "AD AA"],
    "Silvermere Dawn": ["Tank", "AD Fighter", "AP Fighter"],
    "Lightshield Crest": ["Tank"],
    "Aegis of Dusk": ["Tank"],
    "Lich Bane": ["AP Caster", "AP Fighter", "AP AA"],
    "Gold Collector": ["AD Caster", "AD Fighter", "AD AA"],
    "Dawncore": ["AD Caster", "AD Fighter", "AP Caster", "AP Fighter"],
    "Zhonya's Paradox": ["AP Caster", "AP Fighter", "AP AA"],
    "Ahri's Aura": ["AP Caster", "AP Fighter", "AP AA"],
    "Varus's Obsession":["AD Fighter", "AP Fighter", "AD Caster", "AP Caster", "AD AA", "AP AA"],
    "Soraka's Miracle": ["Tank", "AD Fighter", "AP Fighter"],
    "Evelynn's Instinct" : ["AD Fighter", "AP Fighter"],
    "Thresh's Lantern" : ["Tank"],
    "Ekko's Patience" : ["AD Fighter", "AP Fighter", "AD Caster", "AP Caster"],
    "Yasuo's Bladework" : ["AD AA", "AP AA", "AD Caster"],
    "Kayle's Exaltation" : ["Tank", "AD Fighter", "AP Fighter", "AD Caster", "AP Caster", "AD AA", "AP AA"],
    "Kayle's Radiant Exaltation" : ["Tank", "AD Fighter", "AP Fighter", "AD Caster", "AP Caster", "AD AA", "AP AA"],

    # Radiant items
    "Radiant Red Buff": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Radiant Protector's Vow": ["Tank"],
    "Radiant Guinsoo's Rageblade": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Radiant Bramble Vest": ["Tank"],
    "Radiant Adaptive Helm": ["Tank", "AD Caster", "AP Caster", "AP Fighter"],
    "Radiant Titan's Resolve": ["AD Fighter", "AD AA", "AP Fighter", "AP AA"],
    "Radiant Striker's Flail": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Radiant Hextech Gunblade": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Radiant Deathblade": ["AD Caster", "AD Fighter", "AD AA"],
    "Radiant Evenshroud": ["Tank"],
    "Radiant Thief's Gloves": ["Tank", "AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Radiant Giant Slayer": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Radiant Infinity Edge": ["AD Caster", "AD Fighter", "AD AA"],
    "Radiant Morellonomicon": ["AP Caster", "AP Fighter", "AP AA"],
    "Radiant Spear of Shojin": ["AD Caster", "AD Fighter", "AP Caster", "AP Fighter"],
    "Radiant Spirit Visage": ["Tank"],
    "Radiant Steadfast Heart": ["Tank"],
    "Radiant Dragon's Claw": ["Tank"],
    "Radiant Crownguard": ["Tank", "AP Caster", "AP Fighter"],
    "Radiant Warmog's Armor": ["Tank"],
    "Radiant Quicksilver": ["AD Caster", "AD Fighter", "AD AA", "AP Fighter", "AP AA"],
    "Radiant Last Whisper": ["AD Caster", "AD Fighter", "AD AA"],
    "Radiant Ionic Spark": ["Tank"],
    "Radiant Gargoyle Stoneplate": ["Tank"],
    "Radiant Void Staff": ["AP Caster", "AP Fighter", "AP AA"],
    "Radiant Edge of Night": ["AD Fighter", "AP Fighter"],
    "Radiant Hand of Justice": ["AD Caster", "AD Fighter", "AD AA", "AP Caster", "AP Fighter", "AP AA"],
    "Radiant Archangel's Staff": ["AP Caster", "AP Fighter", "AP AA"],
    "Radiant Bloodthirster": ["AD Fighter", "AP Fighter"],
    "Radiant Kraken's Fury": ["AD Caster", "AD Fighter", "AD AA"],
    "Radiant Rabadon's Deathcap": ["AP Caster", "AP Fighter", "AP AA"],
    "Radiant Blue Buff": ["AD Caster", "AD Fighter", "AP Caster", "AP Fighter"],
    "Radiant Jeweled Gauntlet": ["AP Caster", "AP Fighter", "AP AA"],
    "Radiant Nashor's Tooth": ["AP Caster", "AP Fighter"],
    "Radiant Sunfire Cape": ["Tank"],
    "Radiant Sterak's Gage": ["Tank", "AD Fighter", "AP Fighter"]
}